import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {applyIntakeContext, EMPTY_CLINICAL_CONTEXT} from '../src/lib/clinical-context.ts'
import {applyDraft,draftFromProfile,validateDraft} from '../src/lib/profile-edit.ts'
import {buildPlotPoints} from '../src/features/trials/plot-data.ts'
const profile=()=>JSON.parse(fs.readFileSync(new URL('../../tests/fixtures/kras_nsclc.json',import.meta.url)))
test('blank intake preserves reported biomarkers and does not invent ECOG or treatments',()=>{const p=profile();p.biomarkers.msi.status='stable';p.patient_context.ecog=null;p.patient_context.prior_therapies=[];p.patient_context.prior_therapies_known=false;const n=applyIntakeContext(p,EMPTY_CLINICAL_CONTEXT);assert.deepEqual(n,p)})
test('explicit intake context is audited, including ECOG zero and confirmed no treatment',()=>{const p=profile();p.biomarkers.msi.status='stable';const n=applyIntakeContext(p,{...EMPTY_CLINICAL_CONTEXT,msi:'high',ecog:'0',stage:'IV',therapyStatus:'none'});assert.equal(n.patient_context.ecog,0);assert.equal(n.biomarkers.msi.status,'high');assert.equal(n.patient_context.prior_therapies_known,true);assert.deepEqual(n.patient_context.prior_therapies,[]);assert.equal(n.ingestion_provenance.clinician_context[0].changes[0].before,'stable');assert.equal(p.biomarkers.msi.status,'stable')})
test('location is optional and unchanged selected coordinates survive review',()=>{const p=profile();p.patient_context.location={city:'Singapore',country:'Singapore',latitude:1.29,longitude:103.85};let d=draftFromProfile(p);assert.deepEqual(applyDraft(p,d).patient_context.location,p.patient_context.location);d.city='';d.country='';assert.equal(validateDraft(d).city,undefined);assert.equal(applyDraft(p,d).patient_context.location.latitude,null)})
test('unknown and known-empty therapy histories remain different',()=>{const p=profile();const d=draftFromProfile(p);d.therapyStatus='none';assert.equal(applyDraft(p,d).patient_context.prior_therapies_known,true);d.therapyStatus='unknown';assert.equal(applyDraft(p,d).patient_context.prior_therapies_known,false);d.therapyStatus='entered';d.therapies='';assert.ok(validateDraft(d).therapies)})
test('clinical score with unknown access stays scored and retains null geography',()=>{const p=buildPlotPoints([],[{nct_id:'NCT1',title:'Test',clinical_score:40,clinical_assessment:{score_version:'clinical-fit-v3',coverage:.5,status:'provisional'},geography_score:null,distance_km:null}])[0];assert.equal(p.plot_score,40);assert.equal(p.geography_score,null)})
